[Archer]
attack = 2000
cost = 3
defense = 1000
hp = 10000
range = 2
traits = ["Retaliates"]

[BabyDragon]
attack = 3000
cost = 10
defense = 3000
hp = 15000
range = 1
traits = ["Retaliates"]

[BattleSled]
attack = 3000
cost = 5
defense = 2000
hp = 15000
range = 1
traits = ["Retaliates"]

[Catapult]
attack = 4000
cost = 8
defense = 0
hp = 10000
range = 3
traits = []

[Centipede]
attack = 4000
cost = 10
defense = 3000
hp = 20000
range = 1
traits = ["Retaliates"]

[Cloak]
attack = 2000
cost = 8
defense = 500
hp = 5000
range = 1
traits = []

[Crab]
attack = 4000
cost = 10
defense = 4000
hp = 40000
range = 1
traits = ["Retaliates"]

[Dagger]
attack = 2000
cost = 2
defense = 2000
hp = 10000
range = 1
traits = ["Retaliates", "NoRetaliationTaken"]

[Defender]
attack = 1000
cost = 3
defense = 3000
hp = 15000
range = 1
traits = ["Retaliates"]

[Doomux]
attack = 4000
cost = 10
defense = 2000
hp = 20000
range = 1
traits = ["Retaliates"]

[Egg]
attack = 0
cost = 10
defense = 2000
hp = 10000
range = 1
traits = []

[Exida]
attack = 3000
cost = 8
defense = 1000
hp = 10000
range = 3
traits = ["Retaliates", "PoisonOnHit"]

[FireDragon]
attack = 4000
cost = 10
defense = 3000
hp = 20000
range = 2
traits = ["Retaliates"]

[Gaami]
attack = 4000
cost = 10
defense = 3000
hp = 30000
range = 1
traits = ["Retaliates"]

[Giant]
attack = 5000
cost = 10
defense = 4000
hp = 40000
range = 1
traits = ["Retaliates"]

[Hexapod]
attack = 3000
cost = 3
defense = 1000
hp = 5000
range = 1
traits = ["Retaliates"]

[IceArcher]
attack = 0
cost = 3
defense = 1000
hp = 10000
range = 2
traits = ["FreezeOnHit"]

[IceFortress]
attack = 4000
cost = 15
defense = 3000
hp = 20000
range = 2
traits = ["Retaliates"]

[Jelly]
attack = 2000
cost = 8
defense = 2000
hp = 20000
range = 1
traits = ["PreemptiveRetaliation"]

[Juggernaut]
attack = 4000
cost = 10
defense = 4000
hp = 40000
range = 1
traits = []

[Kiton]
attack = 1000
cost = 3
defense = 3000
hp = 15000
range = 1
traits = ["Retaliates", "PoisonOnHit"]

[Knight]
attack = 3500
cost = 8
defense = 1000
hp = 10000
range = 1
traits = ["Retaliates"]

[MindBender]
attack = 0
cost = 5
defense = 1000
hp = 10000
range = 1
traits = ["ConvertOnHit"]

[Mooni]
attack = 0
cost = 5
defense = 1000
hp = 10000
range = 1
traits = []

[Phychi]
attack = 700
cost = 3
defense = 1000
hp = 5000
range = 2
traits = ["Retaliates", "NoRetaliationTaken", "PoisonOnHit"]

[Pirate]
attack = 2000
cost = 2
defense = 1000
hp = 10000
range = 1
traits = ["Retaliates", "NoRetaliationTaken"]

[Polytaur]
attack = 3000
cost = 3
defense = 1000
hp = 15000
range = 1
traits = ["Retaliates"]

[Puffer]
attack = 4000
cost = 8
defense = 0
hp = 10000
range = 3
traits = ["Retaliates"]

[Raychi]
attack = 3000
cost = 8
defense = 2000
hp = 15000
range = 1
traits = ["Retaliates"]

[Rider]
attack = 2000
cost = 3
defense = 1000
hp = 10000
range = 1
traits = ["Retaliates"]

[Segment]
attack = 2000
cost = 1
defense = 1500
hp = 10000
range = 1
traits = []

[Shaman]
attack = 1000
cost = 5
defense = 1000
hp = 10000
range = 1
traits = ["Retaliates", "ConvertOnHit"]

[Shark]
attack = 3500
cost = 8
defense = 2000
hp = 10000
range = 1
traits = ["Retaliates", "NoRetaliationTaken"]

[Swordsman]
attack = 3000
cost = 5
defense = 3000
hp = 15000
range = 1
traits = ["Retaliates"]

[Tridention]
attack = 2500
cost = 8
defense = 1000
hp = 10000
range = 2
traits = ["Retaliates"]

[Warrior]
attack = 2000
cost = 2
defense = 2000
hp = 10000
range = 1
traits = ["Retaliates"]
